### ISSUE TITLE
Implement support for meilisearch

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/backup-restore-sidecar#47]

**Comment by vknabel** [comment]
Depending on the use case, we can either use [dumps or snapshots](https://www.meilisearch.com/docs/learn/advanced/snapshots_vs_dumps).

- snapshots are fast but require exactly the **same** meilisearch version
- dumps require lots of resources during import but are more forward compatible

Use cases:
- snapshots: mainly disaster recovery
- dumps: meilisearch upgrades

**Comment by majst01** [comment]
We actually rotate and create a new index on a daily basis. This means that all indexes older than a day are steady. I suggest that we implement a pure backup solution for these indexes.

**Comment by Gerrit91** [comment]
Yep, and also snapshots are sufficient.

**Comment by Gerrit91** [comment]
Done.
